{% raw %}

NOTEBOOK_TARGET := 'notebooks/*.ipynb'

format-notebooks target=NOTEBOOK_TARGET:
    nbqa isort {{target}}
    nbqa black {{target}}

lint-notebooks target=NOTEBOOK_TARGET:
    nbqa ruff {{target}} --fix || true

update-nix-dependencies:
    niv update

update-python-dependencies:
    poetry update

{% endraw %}
